#
# Docker-compose.yml for MIX front - DEV+STAGE+PROD
#
# ----------------------------------------------------------------
# Changelog:
# 2019-03-21 XEH fetched compse file from server and added to git
# ----------------------------------------------------------------

version: "3"

services:

  nginx:
    image: "nginx"
    
    # name of this docker
    container_name: mix_front_v3

    # volumes mounted in docker
    volumes:
      - ./public_html:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

    working_dir: /home

    ports:
      - 8084:80